# Generated by Django 5.0.6 on 2024-06-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('likes', models.IntegerField()),
                ('caption', models.TextField()),
                ('images', models.JSONField()),
                ('videos', models.JSONField()),
                ('post_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('mediacount', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('followees', models.IntegerField()),
                ('biography', models.TextField()),
                ('profile_pic_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('user_profile', models.URLField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_parsing.instagrampost')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instagram_parsing.instagramprofile'),
        ),
    ]
