# Generated by Django 5.0.6 on 2024-06-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='followees',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='mediacount',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='profile_pic_url',
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram_parsing.instagrampost'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram_parsing.instagramprofile'),
        ),
    ]
