# Generated by Django 5.0.6 on 2024-06-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsing', '0002_remove_instagramprofile_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagrampost',
            old_name='images',
            new_name='post_data',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='post_url',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='videos',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='profile_pic_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='biography',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='followees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='mediacount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='profile_pic_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_parsing.instagrampost'),
        ),
        migrations.AlterField(
            model_name='instagramcomment',
            name='user_profile',
            field=models.CharField(max_length=255),
        ),
    ]
