# Generated by Django 5.0.6 on 2024-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_parsing', '0003_rename_images_instagrampost_post_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaParsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
